### PR TITLE
Big refactorization

### PR DESCRIPTION
**Pull request by aleixalcacer**

### CODE REVIEW

**Comment by aleixalcacer** [comment]
It seems that when you `run hatch env create dev`, it tries to compile the package dependencies from source. Maybe we could change the GitHub workflows to avoid that.

**Comment by wangzcl** [comment]
I noticed the new bug. Let me figure it out.

**Comment by aleixalcacer** [comment]
I think it's because of the old version of scipy, which requires numpy<2.0. However, it seems that the nnls error has been fixed in scipy's main branch on Github.

See: https://github.com/scipy/scipy/blob/main/scipy/optimize/_nnls.py

Maybe we could install scipy from Github. What do you think?

**Comment by wangzcl** [comment]
I found some new conflicts in my fork. Does github allow plain merge instead of rebase when merging a pull request?

**Comment by aleixalcacer** [comment]
> I found some new conflicts in my fork. Does github allow plain merge instead of rebase when merging a pull request?

I have bad experiences with merging without doing a rebase first. How do you update your fork?

The problem is definitely scipy. How would you see using https://github.com/stefanopalmieri/lsqnonneg/blob/master/lsqnonneg.py instead of nnls?

**Comment by wangzcl** [comment]
Let me think about that. SciPy should be working as I remember that NNLS did pass the test on my own computer. I will double check.

**Comment by aleixalcacer** [comment]
> Let me think about that. SciPy should be working as I remember that NNLS did pass the test on my own computer. I will double check.

I've updated it to 1.14 (known issue) to confirm that the issue with numpy was related to scipy. That's why the tests are failing.

**Comment by wangzcl** [comment]
Cheers! Fixed with #44 and #45, however I have noticed another issue that may prevent verbose mode from printing the right iteration step `i`.

**Comment by wangzcl** [comment]
One more thing  in the todo list is update README for python 3.9~3.12

**Comment by aleixalcacer** [comment]
> One more thing in the todo list is update README for python 3.9~3.12

That badge is created automatically from PyPI, using:
https://github.com/aleixalcacer/archetypes/blob/443d09eaad15588e917c36f3ae7cce16d67aa9d9/pyproject.toml#L20-L23

Therefore, when a release is uploaded to PyPI with these new classifiers, the badge will automatically update.

Don't worry about that :)

**Comment by aleixalcacer** [comment]
@wangzcl I noticed an error in the refactoring yesterday. When `transform` is run on an already fitted model, it fails. I've improved the tests to cover this. Previously, `fit_transform` was `fit().transform()`. I think it would be good to keep it that way if possible. I'm not sure if it affects performance. Could you take a look?

**Comment by wangzcl** [comment]
I'll take a look at the bug. I did the refactoring following the [`sklearn` NMF source code](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/decomposition/_nmf.py). They didn't do `fit().transform()` for `fit_transform`, so that additional `transform` step is avoided, making it faster -- I think it is a good design pattern, though it does make things look a little bit weird

**Pull request merged**
